version: '3.8'

services:
  redis:
    image: redis:6-alpine
    container_name: paperless-redis
    restart: always
    networks:
      - findoc_network

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    ports:
      - "8000:8000" 
    environment:
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_URL: http://localhost:8000
    volumes:
      - ./paperless/data:/usr/src/paperless/data
      - ./paperless/media:/usr/src/paperless/media
      - ./paperless/consume:/usr/src/paperless/consume 
    depends_on:
      - redis
      - paperless-db
    networks:
      - findoc_network

  paperless-db:
    image: postgres:13-alpine
    container_name: paperless-db
    restart: always
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - findoc_network

  mysql:
    image: mysql:latest
    container_name: mysql_findoc
    environment:
      MYSQL_ROOT_PASSWORD: nvu1245 
      MYSQL_DATABASE: findoc_db       
    ports:
      - "3307:3306"                      
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  pgdata:

networks:
  findoc_network:
    driver: bridge